name: Release Validation
run-name: Validation for ${{ github.event.pull_request.title }}
on:
  pull_request:
    branches: [master]
env:
  package_dir: ./package
  example_dir: ./example
jobs:
  validation:
    name: Release validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Flutter versioin
        run: flutter --version

      - name: Install dependencies
        working-directory: ${{ env.package_dir }}
        run: flutter pub get

      - uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: ${{ env.package_dir }}

      - uses: fujidaiti/dart-package-inspector@v1.0.0
        with:
          report: ${{ steps.analysis.outputs.json_output }}
          min-pub-points: 130
          supported-platforms: ios, android, linux, windows, macos, web

      - name: Build web app
        working-directory: ${{ env.example_dir }}
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Dry publish
        working-directory: ${{ env.package_dir }}
        run: flutter pub publish --dry-run
